spring.application.name=greeting-service
server.port=8080

greeting-service.greeting=Ola
greeting-service.default-name=Mundo

spring.profiles.active=fr

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.env.show-values=always

spring.config.import=optional:configserver:http://localhost:8888/

eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

eureka.client.healthcheck.enabled=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.description=Microservice Java 2026
info.app.autor=Naubert Piva Migliavacca

eureka.instance.metadata-map.github.repo=naubert-1/API-eletrodomesticos

management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true